choco install -y notepadplusplus
choco install -y sumatrapdf
choco install -y pdfsam
choco install -y filezilla
choco install -y freefilesync
choco install -y gpu-z
choco install -y occt
choco install -y libre-hardware-monitor
choco install -y cpu-z
choco install -y recuva
choco install -y coretemp
choco install -y frhed
choco install -y fsviewer
choco install -y gimp
choco install -y paint.net
choco install -y shotcut
choco install -y obs-studio
choco install -y ffmpeg
choco install -y youtube-dl
choco install -y ffmpeg-batch
choco install -y zoom
choco install -y spacesniffer
choco install -y googleearth
pause